# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{netzke-basepack}
  s.version = "0.6.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Sergei Kozlov"]
  s.date = %q{2010-10-24}
  s.description = %q{A set of full-featured extendible Netzke components (such as FormPanel, GridPanel, Window, BorderLayoutPanel, etc) which can be used as building block for your RIA}
  s.email = %q{sergei@playcode.nl}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".autotest",
     ".gitignore",
     "CHANGELOG.rdoc",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "TODO.rdoc",
     "app/components/netzke/basepack/accordion_panel.rb",
     "app/components/netzke/basepack/basic_app.rb",
     "app/components/netzke/basepack/basic_app/statusbar_ext.js",
     "app/components/netzke/basepack/border_layout_panel.rb",
     "app/components/netzke/basepack/form_panel.rb",
     "app/components/netzke/basepack/form_panel/fields.rb",
     "app/components/netzke/basepack/form_panel/javascripts/netzkefileupload.js",
     "app/components/netzke/basepack/form_panel/javascripts/pre.js",
     "app/components/netzke/basepack/form_panel/javascripts/xcheckbox.js",
     "app/components/netzke/basepack/form_panel/services.rb",
     "app/components/netzke/basepack/grid_panel.rb",
     "app/components/netzke/basepack/grid_panel/columns.rb",
     "app/components/netzke/basepack/grid_panel/javascript.rb",
     "app/components/netzke/basepack/grid_panel/javascripts/advanced_search.js",
     "app/components/netzke/basepack/grid_panel/javascripts/edit_in_form.js",
     "app/components/netzke/basepack/grid_panel/javascripts/pre.js",
     "app/components/netzke/basepack/grid_panel/javascripts/rows-dd.js",
     "app/components/netzke/basepack/grid_panel/multi_edit_form.rb",
     "app/components/netzke/basepack/grid_panel/record_form_window.rb",
     "app/components/netzke/basepack/grid_panel/search_window.rb",
     "app/components/netzke/basepack/grid_panel/services.rb",
     "app/components/netzke/basepack/panel.rb",
     "app/components/netzke/basepack/search_panel.rb",
     "app/components/netzke/basepack/tab_panel.rb",
     "app/components/netzke/basepack/window.rb",
     "app/components/netzke/basepack/wrapper.rb",
     "app/models/netzke_field_list.rb",
     "app/models/netzke_model_attr_list.rb",
     "app/models/netzke_persistent_array_auto_model.rb",
     "autotest/discover.rb",
     "config/database.yml",
     "features/accordion_panel.feature",
     "features/basic_app.feature",
     "features/form_panel.feature",
     "features/grid_panel.feature",
     "features/search_in_grid.feature",
     "features/simple_panel.feature",
     "features/step_definitions/accordion_steps.rb",
     "features/step_definitions/generic_steps.rb",
     "features/step_definitions/grid_panel_steps.rb",
     "features/step_definitions/pickle_steps.rb",
     "features/step_definitions/web_steps.rb",
     "features/support/env.rb",
     "features/support/paths.rb",
     "features/support/pickle.rb",
     "features/tab_panel.feature",
     "features/window.feature",
     "from_05_to_06.rdoc",
     "generators/netzke_basepack/netzke_basepack_generator.rb",
     "generators/netzke_basepack/templates/create_netzke_field_lists.rb",
     "generators/netzke_basepack/templates/public_assets/ts-checkbox.gif",
     "init.rb",
     "install.rb",
     "javascripts/basepack.js",
     "lib/netzke-basepack.rb",
     "lib/netzke/active_record.rb",
     "lib/netzke/active_record/association_attributes.rb",
     "lib/netzke/active_record/attributes.rb",
     "lib/netzke/active_record/combobox_options.rb",
     "lib/netzke/active_record/relation_extensions.rb",
     "lib/netzke/basepack.rb",
     "lib/netzke/basepack/version.rb",
     "lib/netzke/basepack/wrap_lazy_loaded.rb",
     "lib/netzke/data_accessor.rb",
     "lib/netzke/ext.rb",
     "lib/netzke/fields_configurator.rb",
     "lib/netzke/json_array_editor.rb",
     "lib/netzke/masquerade_selector.rb",
     "lib/tasks/netzke_basepack_tasks.rake",
     "locale/en.yml",
     "netzke-basepack.gemspec",
     "spec/active_record/attributes_spec.rb",
     "spec/active_record/relation_extensions_spec.rb",
     "spec/components/form_panel_spec.rb",
     "spec/components/grid_panel_spec.rb",
     "spec/factories.rb",
     "spec/spec_helper.rb",
     "stylesheets/basepack.css",
     "test/console_with_fixtures.rb",
     "test/fixtures/books.yml",
     "test/fixtures/categories.yml",
     "test/fixtures/cities.yml",
     "test/fixtures/continents.yml",
     "test/fixtures/countries.yml",
     "test/fixtures/genres.yml",
     "test/fixtures/roles.yml",
     "test/fixtures/users.yml",
     "test/rails_app/.gitignore",
     "test/rails_app/Gemfile",
     "test/rails_app/Gemfile.lock",
     "test/rails_app/README",
     "test/rails_app/Rakefile",
     "test/rails_app/app/components/generic_user_form.rb",
     "test/rails_app/app/components/simple_accordion.rb",
     "test/rails_app/app/components/simple_basic_app.rb",
     "test/rails_app/app/components/simple_panel.rb",
     "test/rails_app/app/components/simple_tab_panel.rb",
     "test/rails_app/app/components/simple_wrapper.rb",
     "test/rails_app/app/components/some_border_layout.rb",
     "test/rails_app/app/components/some_search_panel.rb",
     "test/rails_app/app/components/some_tab_panel.rb",
     "test/rails_app/app/components/user_form.rb",
     "test/rails_app/app/components/user_form_with_default_fields.rb",
     "test/rails_app/app/components/user_grid.rb",
     "test/rails_app/app/components/window_component_loader.rb",
     "test/rails_app/app/controllers/application_controller.rb",
     "test/rails_app/app/controllers/components_controller.rb",
     "test/rails_app/app/controllers/welcome_controller.rb",
     "test/rails_app/app/helpers/application_helper.rb",
     "test/rails_app/app/models/role.rb",
     "test/rails_app/app/models/user.rb",
     "test/rails_app/app/presenters/forms/generic_user.rb",
     "test/rails_app/app/views/layouts/application.html.erb",
     "test/rails_app/config.ru",
     "test/rails_app/config/application.rb",
     "test/rails_app/config/boot.rb",
     "test/rails_app/config/database.yml",
     "test/rails_app/config/environment.rb",
     "test/rails_app/config/environments/development.rb",
     "test/rails_app/config/environments/production.rb",
     "test/rails_app/config/environments/test.rb",
     "test/rails_app/config/initializers/backtrace_silencers.rb",
     "test/rails_app/config/initializers/inflections.rb",
     "test/rails_app/config/initializers/mime_types.rb",
     "test/rails_app/config/initializers/netzke.rb",
     "test/rails_app/config/initializers/secret_token.rb",
     "test/rails_app/config/initializers/session_store.rb",
     "test/rails_app/config/locales/es.yml",
     "test/rails_app/config/routes.rb",
     "test/rails_app/db/development_structure.sql",
     "test/rails_app/db/migrate/20100905214933_create_netzke_preferences.rb",
     "test/rails_app/db/migrate/20100914104207_create_users.rb",
     "test/rails_app/db/migrate/20100914104236_create_roles.rb",
     "test/rails_app/db/schema.rb",
     "test/rails_app/db/seeds.rb",
     "test/rails_app/features/support/paths.rb",
     "test/rails_app/lib/tasks/.gitkeep",
     "test/rails_app/public/404.html",
     "test/rails_app/public/422.html",
     "test/rails_app/public/500.html",
     "test/rails_app/public/favicon.ico",
     "test/rails_app/public/images/header-deco.gif",
     "test/rails_app/public/images/rails.png",
     "test/rails_app/public/javascripts/application.js",
     "test/rails_app/public/javascripts/controls.js",
     "test/rails_app/public/javascripts/dragdrop.js",
     "test/rails_app/public/javascripts/effects.js",
     "test/rails_app/public/javascripts/prototype.js",
     "test/rails_app/public/javascripts/rails.js",
     "test/rails_app/public/robots.txt",
     "test/rails_app/public/stylesheets/.gitkeep",
     "test/rails_app/script/rails",
     "test/rails_app/spec/models/role_spec.rb",
     "test/rails_app/spec/models/user_spec.rb",
     "test/rails_app/test/performance/browsing_test.rb",
     "test/rails_app/test/test_helper.rb",
     "test/rails_app/tmp/restart.txt",
     "test/rails_app/vendor/plugins/.gitkeep",
     "test/schema.rb",
     "test/test_helper.rb",
     "test/unit/accordion_panel_test.rb",
     "test/unit/active_record_basepack_test.rb",
     "test/unit/fields_configuration_test.rb",
     "test/unit/grid_panel_test.rb",
     "test/unit/netzke_basepack_test.rb",
     "test/unit/tab_panel_test.rb",
     "uninstall.rb"
  ]
  s.homepage = %q{http://github.com/skozlov/netzke-basepack}
  s.post_install_message = %q{
========================================================================

           Thanks for installing Netzke Basepack!
           
  Don't forget to run "./script/generate netzke_basepack" for each 
  Rails app that will be using this gem.

  Netzke home page:     http://netzke.org
  Netzke Google Groups: http://groups.google.com/group/netzke
  Netzke tutorials:     http://blog.writelesscode.com

========================================================================

}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Pre-built Rails + ExtJS components for your RIA}
  s.test_files = [
    "spec/active_record/attributes_spec.rb",
     "spec/active_record/relation_extensions_spec.rb",
     "spec/components/form_panel_spec.rb",
     "spec/components/grid_panel_spec.rb",
     "spec/factories.rb",
     "spec/spec_helper.rb",
     "test/console_with_fixtures.rb",
     "test/rails_app/app/components/generic_user_form.rb",
     "test/rails_app/app/components/simple_accordion.rb",
     "test/rails_app/app/components/simple_basic_app.rb",
     "test/rails_app/app/components/simple_panel.rb",
     "test/rails_app/app/components/simple_tab_panel.rb",
     "test/rails_app/app/components/simple_wrapper.rb",
     "test/rails_app/app/components/some_border_layout.rb",
     "test/rails_app/app/components/some_search_panel.rb",
     "test/rails_app/app/components/some_tab_panel.rb",
     "test/rails_app/app/components/user_form.rb",
     "test/rails_app/app/components/user_form_with_default_fields.rb",
     "test/rails_app/app/components/user_grid.rb",
     "test/rails_app/app/components/window_component_loader.rb",
     "test/rails_app/app/controllers/application_controller.rb",
     "test/rails_app/app/controllers/components_controller.rb",
     "test/rails_app/app/controllers/welcome_controller.rb",
     "test/rails_app/app/helpers/application_helper.rb",
     "test/rails_app/app/models/role.rb",
     "test/rails_app/app/models/user.rb",
     "test/rails_app/app/presenters/forms/generic_user.rb",
     "test/rails_app/config/application.rb",
     "test/rails_app/config/boot.rb",
     "test/rails_app/config/environment.rb",
     "test/rails_app/config/environments/development.rb",
     "test/rails_app/config/environments/production.rb",
     "test/rails_app/config/environments/test.rb",
     "test/rails_app/config/initializers/backtrace_silencers.rb",
     "test/rails_app/config/initializers/inflections.rb",
     "test/rails_app/config/initializers/mime_types.rb",
     "test/rails_app/config/initializers/netzke.rb",
     "test/rails_app/config/initializers/secret_token.rb",
     "test/rails_app/config/initializers/session_store.rb",
     "test/rails_app/config/routes.rb",
     "test/rails_app/db/migrate/20100905214933_create_netzke_preferences.rb",
     "test/rails_app/db/migrate/20100914104207_create_users.rb",
     "test/rails_app/db/migrate/20100914104236_create_roles.rb",
     "test/rails_app/db/schema.rb",
     "test/rails_app/db/seeds.rb",
     "test/rails_app/features/support/paths.rb",
     "test/rails_app/spec/models/role_spec.rb",
     "test/rails_app/spec/models/user_spec.rb",
     "test/rails_app/test/performance/browsing_test.rb",
     "test/rails_app/test/test_helper.rb",
     "test/schema.rb",
     "test/test_helper.rb",
     "test/unit/accordion_panel_test.rb",
     "test/unit/active_record_basepack_test.rb",
     "test/unit/fields_configuration_test.rb",
     "test/unit/grid_panel_test.rb",
     "test/unit/netzke_basepack_test.rb",
     "test/unit/tab_panel_test.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<netzke-core>, ["~> 0.6.0"])
      s.add_runtime_dependency(%q<meta_where>, [">= 0.9.3"])
      s.add_runtime_dependency(%q<will_paginate>, ["~> 3.0.pre2"])
      s.add_runtime_dependency(%q<acts_as_list>, [">= 0"])
    else
      s.add_dependency(%q<netzke-core>, ["~> 0.6.0"])
      s.add_dependency(%q<meta_where>, [">= 0.9.3"])
      s.add_dependency(%q<will_paginate>, ["~> 3.0.pre2"])
      s.add_dependency(%q<acts_as_list>, [">= 0"])
    end
  else
    s.add_dependency(%q<netzke-core>, ["~> 0.6.0"])
    s.add_dependency(%q<meta_where>, [">= 0.9.3"])
    s.add_dependency(%q<will_paginate>, ["~> 3.0.pre2"])
    s.add_dependency(%q<acts_as_list>, [">= 0"])
  end
end

