source 'http://rubygems.org'

gem 'rails', '3.0.1'

gem 'netzke-core'#, :git => "~/code/netzke/netzke-core"
gem 'netzke-persistence'#, :git => "~/code/netzke/netzke-persistence"

gem 'will_paginate', '3.0.pre2'
gem 'meta_where'
gem 'acts_as_list'

# Bundle gems for the local environment. Make sure to
# put test-only gems in this group so their generators
# and rake tasks are available in development mode:
group :development, :test do
  gem 'capybara'
  gem 'cucumber-rails'
  gem 'cucumber'
  gem 'rspec-rails'
  gem 'spork'
  gem 'launchy'    # So you can do Then show me the page
  gem 'factory_girl'
end

group :development do
  gem 'mysql2'
end

group :test do
  gem 'sqlite3-ruby', :require => 'sqlite3'
  gem 'pickle'
  gem 'database_cleaner'#, :git => 'http://github.com/bmabey/database_cleaner.git'
end