source 'http://rubygems.org'

gem 'rails', '3.0.0'

gem 'will_paginate', '3.0.pre2'
gem 'meta_where'

# Bundle gems for the local environment. Make sure to
# put test-only gems in this group so their generators
# and rake tasks are available in development mode:
group :development, :test do
  gem 'capybara'
  gem 'database_cleaner'
  gem 'cucumber-rails'
  gem 'cucumber'
  gem 'rspec-rails', ">= 2.0.0.beta.19"
  gem 'spork'
  gem 'launchy'    # So you can do Then show me the page
end

group :development do
  gem 'mysql2'
end

group :test do
  gem 'sqlite3-ruby', :require => 'sqlite3'
end