source 'http://rubygems.org'

# we are getting AR still regardless of ORM env, because netzke-persistence needs it
gem 'rails', '~>3.2.0'
gem 'mysql2'

gem 'netzke-core',        :path => File.expand_path('../vendor/gems', __FILE__)

group :test do
  gem 'factory_girl'
  gem 'selenium-webdriver'
  gem 'launchy'    # So you can do Then show me the page
  gem 'capybara'
  gem 'cucumber-rails'
  gem 'cucumber'
  gem 'rspec-rails'
  gem 'spork'

  # gem 'sqlite3-ruby', :require => 'sqlite3'
  gem 'pickle'
  gem 'database_cleaner'
end
